{
    getTests(jql: "project = MCA AND issuetype = Test AND testType = Cucumber AND status IN ('Ready for Implementation', 'In Development', 'In Deployment', 'Done')", limit: 100, start: $start) {
        total
        start
        limit
        results {
            gherkin
            jira(fields: ["key", "summary", "labels", "issuelinks", "created", "updated"])
        }
    }
}
